my_name: uav1

vehicle:
  autopilot: FCAutopilotType.PX4
  uav_type: UAVType.Copter
  telem_type: TelemType.Mavlink2

core:
  name: test_takeoff_land
  cfg:
    id: mav_core
    mav_port: 14540

    mission:
      takeoff_altitude_m: 10.0
      takeoff_altitude_ok_fraction: 0.8
      post_takeoff_wait_s: 5.0
      go_north_distance_m: 50.0
      goto_arrival_radius_m: 1.0
      goto_yaw_deg: 0.0
      target_altitude_m: 25.0
      altitude_tolerance_m: 1.0
      altitude_change_timeout_s: 120.0
      home_arrival_radius_m: 1.0
      land_altitude_threshold_m: 0.5
      poll_interval_s: 0.5
      goto_timeout_s: 120.0
      rtl_timeout_s: 180.0
      land_timeout_s: 120.0
      state_timeout_s: 60.0
      response_timeout_s: 20.0

    state_keys:
    - IsHomePositionOk
    - IsGlobalPositionOk
    - IsArmed
    - IsInAir
    - AltitudeM
    - Position
    - SensorConfig
    - ActiveModeNames

    state_logging:
      keys:
      - IsInAir
      - IsArmed
      - AltitudeM
      interval_s: 0.5
      prefix: CORE

bus_config:
  schema_path: ../../config/bus_topics_schema.json
  log_file: hivebus.log
  endpoint:
    type: mqtt
    host: 127.0.0.1
    port: 1883

plugins:
- plugin: px4_sitl_gz_launcher
  cfg:
    id: px4_sitl
    auto_start: true

    px4:
      px4_dir: "../../../other_software/PX4-Autopilot/"
      sitl_vehicle: "gz_x500_mono_cam"
      companion_mavlink_port: 14540
      qgc_mavlink_port: 14550
      qgc_mavlink_enabled: true
      qgc_local_port: 18571
      home_lat: 36.529973
      home_lon: -83.218791
      home_alt: 0
      model_pose: ""

    gazebo:
      gz_world: "default"
      gz_ip: 127.0.0.1
      gz_gui: true
      video_host_ip: 127.0.0.1
      video_host_port: 5601
    
- plugin: uav_controller
  cfg:
    id: uav_controller
    topic_ns: UAV
    poll_interval_s: 0.1
    response_timeout_s: 20.0

- plugin: mavsdk_interface
  cfg:
    id: mavsdk
    topic_ns: UAV
    is_interface: true
    conn_type: udp
    conn_str: udp://:<mav_port>
    mav_dialect: PX4
    mav_type: MAV_TYPE_QUADROTOR
    mav_sysid: 1
    mavsdk_log_debug: false
    state_intervals:
      IsInAir: 0.1
      IsArmed: 0.1
      IsHomePositionOk: 0.5
      IsGlobalPositionOk: 0.5
      AltitudeM: 0.1
      Position: 0.2
      AttitudeRad: 0.1
      AngVelRadS: 0.1
      FixType: 0.5
      NumSat: 0.5
      GpsInfo: 0.5
      RawGps: 0.5
      Battery: 0.5
      Imu: 0.1
      FcInfo: 1.0
      FlightMode: 0.2
      SensorConfig: 1.0
      ActiveModeNames: 0.2
