my_name: uav1
vehicle:
  autopilot: Autopilot.INAV
  airframe: Airframe.COPTER
  telem_type: Telemetry.MSP
core:
  name: example_msp
  cfg:
    id: example_msp_core
    poll_interval_s: 0.1
    print_interval_s: 1.0
    state_timeout_s: 20.0
    response_timeout_s: 20.0

bus_config:
  schema_path: ../../config/bus_topics_schema.json
  log_file: hivebus.log
  endpoint:
    type: mqtt
    host: 127.0.0.1
    port: 1883
plugins:
- plugin: uav_controller
  cfg:
    id: uav_controller
    topic_ns: UAV
    poll_interval_s: 0.1
    response_timeout_s: 20.0
- plugin: msp_interface
  cfg:
    id: mspapi
    topic_ns: UAV
    is_interface: true
    conn_type: tcp
    conn_str: localhost:5760
    conn_bitrate: 115200
    conn_read_timeout_s: 0.05
    conn_write_timeout_s: 0.2
    conn_max_retries: 1
    conn_reconnect_delay_s: 0.5
    state_intervals:
      flight_control: 0.2
      location: 0.2
      attitude: 0.1
      angular_velocity: 0.1
      gnss: 0.5
      power: 0.5
      imu: 0.2
      rc_telemetry: 0.2
      control_override: 0.2
      control_output: 0.2
      runtime_load: 0.5
