my_name: uav1
core:
  name: example_liftoff
  cfg:
    id: example_liftoff_core
    poll_interval_s: 0.1
    print_interval_s: 1.0
    state_timeout_s: 20.0
    interface:
      id: liftoff
      topic_ns: UAV

bus_config:
  schema_path: ../../config/bus_topics_schema.json
  log_file: hivebus.log
  endpoint:
    type: mqtt
    host: 127.0.0.1
    port: 1883

plugins:
- plugin: liftoff_interface
  cfg:
    id: liftoff
    topic_ns: UAV
    is_interface: true
    telemetry_host: 0.0.0.0
    telemetry_port: 9001
    socket_timeout_s: 0.2
    link_timeout_s: 1.0
    packet_buffer_size: 1024
    in_air_alt_threshold: 0.5
    state_intervals:
      FcConnected: 0.2
      SensorConfig: 1.0
      FlightMode: 0.5
      IsInAir: 0.2
      AltitudeM: 0.1
      AttitudeRad: 0.1
      RcTelemetry: 0.1
      Battery: 0.5
      Analog: 0.5
