my_name: uav1

vehicle:
  autopilot: Autopilot.PX4
  airframe: Airframe.COPTER
  telem_type: Telemetry.MAVLINK

core:
  name: execution_host
  cfg:
    id: execution_host
    poll_interval_s: 0.25

bus_config:
  schema_path: ../../config/bus_topics_schema.json
  log_file: hivebus.log
  endpoint:
    type: mqtt
    host: 127.0.0.1
    port: 1883

plugins:
- plugin: px4_sitl_gz_launcher
  cfg:
    id: px4_sitl
    auto_start: true
    px4:
      # Override without editing this file by setting PX4_AUTOPILOT_PATH.
      px4_dir: ../PX4-Autopilot
      sitl_vehicle: gz_x500
      airframe_vehicle: gz_x500
      companion_mavlink_port: 14540
      qgc_mavlink_port: 14550
      qgc_mavlink_enabled: false
      qgc_local_port: 18571
      home_lat: 47.397742
      home_lon: 8.545594
      home_alt: 488
      model_pose: ""
    gazebo:
      gz_world: default
      gz_ip: 127.0.0.1
      gz_gui: true
      video_host_ip: 127.0.0.1
      video_host_port: 5601

- plugin: execution_ingress
  cfg:
    id: execution_ingress
    topic_ns: EXECUTION
    auto_takeoff_for_move: true
    asset_id: <my_name>

- plugin: uav_controller
  cfg:
    id: uav_controller
    topic_ns: UAV
    poll_interval_s: 0.1
    response_timeout_s: 20.0

- plugin: mavsdk_interface
  cfg:
    id: mavsdk
    topic_ns: UAV
    is_interface: true
    conn_type: udp
    conn_str: udpin://0.0.0.0:14540
    mav_dialect: PX4
    mav_type: MAV_TYPE_QUADROTOR
    mav_sysid: 1
    mavsdk_log_debug: false
    state_intervals:
      flight_control: 0.1
      location: 0.1
      attitude: 0.1
      angular_velocity: 0.1
      gnss: 0.5
      power: 0.5
      firmware: 1.0
